### ISSUE TITLE
[Suggestion] Long shot backport

### ISSUE THREAD

**Issue by itsdinkd** [4drian3d/ClientCatcher#39]
Hi,

This is a longshot, but I came across your mod and I fell in love. Can you please back port this to 1.19.2?

Reason being; 1.19.2 is still the most popular 1.19.x version, with all large modpacks still on 1.19.2, mine included, and have no plans on updating to 1.19.3 or 1.19.4. We are waiting for 1.20 to update.

Check curseforge for example. 

### Here are the 1.19.2 Fabric modpacks
**888 Projects found**
![image](https://user-images.githubusercontent.com/35115304/234967241-82b1a04d-14cf-47ad-8d84-7b48e31183d0.png)
https://www.curseforge.com/minecraft/search?page=1&class=modpacks&gameFlavorsIds=4&gameVersion=1.19.2&sortType=1&pageSize=20

### 1.19.3 Fabric Modpacks
**193 Projects found**
![image](https://user-images.githubusercontent.com/35115304/234967567-9a060ea1-1d78-4102-b188-245599a6adc7.png)
https://www.curseforge.com/minecraft/search?page=1&class=modpacks&gameFlavorsIds=4&gameVersion=1.19.3&sortType=1&pageSize=20

### 1.19.4 Fabric Modpacks
**94 Projects found**
![image](https://user-images.githubusercontent.com/35115304/234967520-70b32db8-a071-4b47-916f-7960525dfa5c.png)
https://www.curseforge.com/minecraft/search?page=1&class=modpacks&gameFlavorsIds=4&gameVersion=1.19.4&sortType=1&pageSize=20

If you visit these links you will see no major modpack on 1.19.3 or 1.19.4 aside from the optimization modpacks.

## If you backport to 1.19.2, I can guarantee that you will have more downloads.
I feel like this is such a useful mod and it deserves more attention across the board.

**Comment by 4drian3d** [comment]
What? This project is not a mod, it is a plugin for Velocity and supports any version from 1.7.10 to 1.19.4 (and 1.20 when Velocity supports it)

**Comment by 4drian3d** [comment]
You may be confused for some reason with [MiniPlaceholders](https://github.com/MiniPlaceholders/MiniPlaceholders), which I don't plan to backport it to Fabric 1.19.3 or lower

**Comment by itsdinkd** [comment]
Oh weird. i could have sworn i saw fabric on modrinth. but yes I did find this plugin through Mini Placeholders. apologies

**Comment by itsdinkd** [comment]
that being said, you should totally make this a mod :)

**Comment by 4drian3d** [comment]
> that being said, you should totally make this a mod :)

I do not discard porting this plugin to Paper and Fabric, but it will take me some time to do it and first I have to finish other things in my other plugins
